feat: Update to Gatsby Starter
medusajs/gatsby-starter-medusa-simple pull request #4
Opened 2021-06-28 08:57 UTC by kasperkristensen

2021-06-28 10:49 UTC, olivermrbl requested changes
To bigger things, that we could start out with:
- Let's rename all files to a `kebab-cased` version
- Let's try to include our `medusa-js` client instead of the `services/api.js`. You can install the latest version by doing `yarn add @medusajs/medusa-js@canary`.

The client should be initialised by creating a util function like so: 
```
import Medusa from "@medusajs/medusa-js"

const BACKEND_URL = process.env.GATSBY_STORE_URL || "http://localhost:4000"

export const createClient = () => new Medusa({ baseUrl: BACKEND_URL })
```

But feel free, to do it your preferred way :)

2021-06-28 11:51 UTC, kasperkristensen commented
> Two bigger things, that we could start out with:
> 
> * Let's rename all files to a `kebab-cased` version
> * Let's try to include our `medusa-js` client instead of the `services/api.js`. You can install the latest version by doing `yarn add @medusajs/medusa-js@canary`.
> 
> The client should be initialised by creating a util function like so:
> 
> ```
> import Medusa from "@medusajs/medusa-js"
> 
> const BACKEND_URL = process.env.GATSBY_STORE_URL || "http://localhost:4000"
> 
> export const createClient = () => new Medusa({ baseUrl: BACKEND_URL })
> ```
> 
> But feel free, to do it your preferred way :)

Made the requested changes, have a look :)

2021-06-28 12:21 UTC, olivermrbl requested changes
Some additional minor changes 😄 

And let's also rename all styling files to `kebab-case`

2021-06-28 12:21 UTC, olivermrbl commented on src/components/cartView/cart-view.jsx
> +import { quantity, sum, formatPrice } from "../../utils/helperFunctions";
Should be `helper-functions`

2021-06-28 12:21 UTC, olivermrbl commented on src/components/cartView/cart-view.jsx
> +          disabled={cart.items.length < 1 ? true : ""}
Why not `false`?

2021-06-28 12:21 UTC, olivermrbl commented on src/components/checkout/checkout-summery.jsx
> +const CheckoutSummery = ({ cart }) => {
Rename to `CheckoutSummary`

2021-06-28 12:21 UTC, olivermrbl commented on src/components/checkout/information-step.jsx
> +          country_code: "Denmark",
Should not be fixed. Please use country from region.

2021-06-28 12:21 UTC, olivermrbl commented on src/components/checkout/injectable-card.jsx
> +const InjectableCard = () => {
Rename to `InjectablePaymentCard` 👍

2021-06-28 12:21 UTC, olivermrbl commented on src/components/checkout/payment-step.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Would it have any negative consequences to simply include it as dependency?

2021-06-28 12:21 UTC, olivermrbl commented on src/context/display-context.js
> +
General comment: Rename everything from summery -> summary 👍

2021-06-28 12:21 UTC, olivermrbl commented on src/pages/product/[id].js
> +        });
Not sure, that I understand this condition. Please elaborate :)

2021-06-28 13:48 UTC, kasperkristensen commented on src/components/cartView/cart-view.jsx
> +          disabled={cart.items.length < 1 ? true : ""}
Old habbit, but changed now :)

2021-06-28 13:48 UTC, kasperkristensen commented on src/components/checkout/payment-step.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
It creates a loop

2021-06-28 13:49 UTC, kasperkristensen commented on src/pages/product/[id].js
> +        });
Changed it to allow it as long as the quantity is less than inventory :)

2021-06-28 18:57 UTC, olivermrbl requested changes
A final, final comment in regards to the styling 😄  
Let's also lowercase all the styling files, that was not `kebab-cased` in previous commit.

![image](https://user-images.githubusercontent.com/59018053/123689381-731b8280-d853-11eb-97d5-0b308021348b.png)

2021-06-28 18:57 UTC, olivermrbl commented on src/pages/index.js
> +              href="https://github.com/medusajs/nextjs-starter-medusa"
`https://github.com/medusajs/gatsby-starter-medusa`

2021-06-29 07:26 UTC, olivermrbl approved these changes
Great job!! Let's ship it 🚀

2021-06-29 07:36 UTC, merged